# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: all
BASH_FILTER_REGEX_EXCLUDE: "(lib)"
CONFIG_REPORTER: false
DISABLE_LINTERS:
  - ANSIBLE_ANSIBLE_LINT
  - EDITORCONFIG_EDITORCONFIG_CHECKER
  - JAVASCRIPT_ES
  - JSON_NPM_PACKAGE_JSON_LINT
  - JSX_ESLINT
  - KUBERNETES_KUBECONFORM
  - KUBERNETES_HELM
  - KUBERNETES_KUBESCAPE
  - REPOSITORY_LS_LINT
  - SALESFORCE_SFDX_SCANNER_APEX
  - SALESFORCE_SFDX_SCANNER_AURA
  - SALESFORCE_SFDX_SCANNER_LWC
  - SALESFORCE_LIGHTNING_FLOW_SCANNER
  - SPELL_PROSELINT
  - SPELL_VALE
  - SQL_SQLFLUFF
  - SWIFT_SWIFTLINT
  - TSX_ESLINT
  - TYPESCRIPT_ES
  - TYPESCRIPT_PRETTIER
EMAIL_REPORTER: false
FLAVOR_SUGGESTIONS: true
GITHUB_COMMENT_REPORTER: true
GITHUB_STATUS_REPORTER: true
JSON_JSONLINT_FILTER_REGEX_EXCLUDE: '(\.vscode/)'
PRINT_ALL_FILES: false
REPORTERS_MARKDOWN_SUMMARY_TYPE: sections
SARIF_REPORTER: true
SHOW_ELAPSED_TIME: true
TEXT_REPORTER: false
YAML_PRETTIER_FILTER_REGEX_EXCLUDE: '(templates/\.mega-linter\.yml|mkdocs\.yml)'
YAML_V8R_FILTER_REGEX_EXCLUDE: '(descriptors|templates/\.mega-linter\.yml|\.codecov\.yml)'
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: '(templates/\.mega-linter\.yml)'
UPDATED_SOURCES_REPORTER: false
