name: Automerge PRs

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    uses: tkhom3/gha-workflows/.github/workflows/automerge-prs.yml@332d3a51b15d2f7c36e8ab6525d8d9ae2de8e969 # v1.0.12
    secrets:
      token: ${{ secrets.GHA_PAT }}
