name: Automerge PRs

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    uses: tkhom3/gha-workflows/.github/workflows/automerge-prs.yml@aa66c6cf2188919b4e79194010e779c6c6833b27 # v1.0.13
    secrets:
      token: ${{ secrets.GHA_PAT }}
