name: Automerge PRs

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    uses: tkhom3/gha-workflows/.github/workflows/automerge-prs.yml@edbfb65bf4718daa5e02dc5bcc40b0fdf8018143 # v1.0.22
    secrets:
      token: ${{ secrets.GHA_PAT }}
