name: Create Release, Build and Deploy Image

on:
  workflow_call:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v5

      - name: Release Please
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release
        with:
          release-type: simple
          token: ${{ secrets.GHA_PAT }}

      - name: Login to DockerHub
        if: ${{ steps.release.outputs.release_created }}
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        if: ${{ steps.release.outputs.release_created }}
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          context: .
          push: true
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ steps.release.outputs.version }}
            ${{ github.repository }}:${{ steps.release.outputs.major }}
            ${{ github.repository }}:${{ github.ref_name }}
            ${{ github.repository }}:${{ github.sha }}
