name: Scan with Codacy on PR

on:
  workflow_call:

jobs:
  codacy-security-scan:
    name: Code Scan
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@v4.1.0
        with:
          output: codacy-results
          format: table
          exit-code: 1

      - name: Post to PR
        uses: EliLillyCo/github-actions-post-to-pr@1.2
        if: ${{ failure() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          post_to_pr_definition: |
            [
              {
                "message_file": "codacy-results",
                "title": "Codacy Image Scan Results"
              }
            ]
