name: Scan with Trivy on PR
on:
  workflow_call:

permissions:
  pull-requests: write

jobs:
  image:
    name: Scan image
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - id: string
      uses: ASzc/change-string-case-action@v6
      with:
        string: ${{ github.repository }}
        
    - name: Build an image from Dockerfile
      run: |
          docker build -t docker.io/${{ steps.string.outputs.lowercase }}:${{ github.sha }} .

    - name: Run Trivy image vulnerability scanner
      uses: aquasecurity/trivy-action@0.16.0
      with:
        image-ref: 'docker.io/${{ steps.string.outputs.lowercase }}:${{ github.sha }}'
        scan-type: image
        security-checks: vuln,secret,config
        severity: CRITICAL,HIGH,MEDIUM
        ignore-unfixed: true
        exit-code: 1
        format: table
        output: trivy-results
        trivyignores: '.trivyignore'

    - name: Post to PR
      uses: EliLillyCo/github-actions-post-to-pr@1.2
      if: ${{ failure() }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        post_to_pr_definition: |
          [
            {
              "message_file": "trivy-results",
              "title": "Trivy Image Scan Results"
            }
          ]

  iac:
    name: Scan IaC
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Trivy Misconfiguration - IaC
      uses: aquasecurity/trivy-action@0.16.0
      with:
        scan-type: config
        severity: CRITICAL,HIGH,MEDIUM
        ignore-unfixed: true
        exit-code: 1
        format: table
        output: trivy-results
        trivyignores: '.trivyignore'

    - name: Post to PR
      uses: EliLillyCo/github-actions-post-to-pr@1.2
      if: ${{ failure() }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        post_to_pr_definition: |
          [
            {
              "message_file": "trivy-results",
              "title": "Trivy IaC Misconfigurations"
            }
          ]
