name: Scan with Trivy - Config Only
on:
  workflow_call:

permissions:
  pull-requests: write

jobs:
  iac:
    name: Scan IaC
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Trivy Misconfiguration - IaC
      uses: aquasecurity/trivy-action@0.9.1
      with:
        scan-type: config
        severity: CRITICAL,HIGH,MEDIUM
        ignore-unfixed: true
        exit-code: 1
        format: table
        output: trivy-results
        trivyignores: '.trivyignore'

    - name: Post to PR
      uses: EliLillyCo/github-actions-post-to-pr@1.2
      if: ${{ failure() }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        post_to_pr_definition: |
          [
            {
              "message_file": "trivy-results",
              "title": "Trivy IaC Misconfigurations"
            }
          ]
