name: Scan with Trivy
on:
  workflow_call:
  
jobs:
  build:
    name: Scan with Trivy
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - id: string
      uses: ASzc/change-string-case-action@v6
      with:
        string: ${{ github.repository }}
        
    - name: Build an image from Dockerfile
      run: |
          docker build -t docker.io/${{ steps.string.outputs.lowercase }}:${{ github.sha }} .
          
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.30.0
      with:
        image-ref: 'docker.io/${{ steps.string.outputs.lowercase }}:${{ github.sha }}'
        scan-type: image
        scanners: vuln
        severity: CRITICAL,HIGH,MEDIUM
        ignore-unfixed: true
        exit-code: 0
        format: sarif
        output: trivy-vuln-results.sarif
        
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-vuln-results.sarif'
        category: 'Trivy Image Vulnerability'

  sbom:
    name: Generate SBOM
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy in GitHub SBOM mode and submit results to Dependency Graph
      uses: aquasecurity/trivy-action@0.30.0
      with:
        scan-type: 'fs'
        format: 'github'
        output: 'dependency-results.sbom.json'
        image-ref: '.'
        github-pat: ${{ secrets.GITHUB_TOKEN }}
