name: Scan with Trivy - Config Only
on:
  workflow_call:

permissions:
  security-events: write

jobs:
  scan:
    name: Scan with Trivy
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Trivy Misconfiguration - IaC
      uses: aquasecurity/trivy-action@0.8.0
      with:
        scan-type: config
        hide-progress: false
        severity: CRITICAL,HIGH,MEDIUM
        ignore-unfixed: true
        exit-code: 0
        format: sarif
        output: trivy-misconfig-results.sarif

    - name: Upload Trivy vuln results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: trivy-misconfig-results.sarif
        category: Trivy Misconfiguration
